export const metadata = {
  title: 'AI Ethics & Copyright Disclaimer | PetiBoo',
  description:
    'AI Ethics, transparency, and copyright disclaimer for PetiBoo, operated by Oasis Software Technology Limited.',
};

export default function AIEthicsPage() {
  return (
    <main className="mx-auto w-full max-w-5xl px-6 py-12">
      <header className="mb-10">
        <h1 className="text-4xl font-bold tracking-tight text-slate-900">
          AI Ethics & Copyright Disclaimer
        </h1>
        <p className="mt-3 text-sm text-slate-600">
          <strong>Last updated:</strong> 25 December 2025
        </p>
      </header>

      <section className="prose prose-slate max-w-none">
        <p>
          This AI Ethics & Copyright Disclaimer explains how artificial
          intelligence (“AI”) is used on <strong>PetiBoo</strong> and clarifies
          the ethical principles, copyright considerations, and limitations
          associated with AI-generated content.
        </p>

        <p>
          PetiBoo is operated by <strong>Oasis Software Technology Limited</strong>
          (“Company”, “We”, “Us”, or “Our”). By using our Service, you acknowledge
          and accept the terms described in this document.
        </p>

        <h2>1. Use of Artificial Intelligence</h2>
        <p>
          PetiBoo uses artificial intelligence models to generate original
          caricature-style images based on photos uploaded by users.
        </p>

        <ul>
          <li>AI outputs are generated algorithmically</li>
          <li>No human artist manually edits or draws the images</li>
          <li>Results may vary depending on image quality and input data</li>
        </ul>

        <h2>2. Ethical AI Principles</h2>
        <p>
          We are committed to responsible and ethical use of AI technologies.
          Our principles include:
        </p>

        <ul>
          <li>
            <strong>Transparency:</strong> Users are informed when content is
            generated by AI.
          </li>
          <li>
            <strong>Fair Use:</strong> AI outputs are designed to be original and
            transformative.
          </li>
          <li>
            <strong>User Control:</strong> Users choose what content to upload
            and generate.
          </li>
          <li>
            <strong>Privacy Protection:</strong> Uploaded images are processed
            only to deliver the Service.
          </li>
        </ul>

        <h2>3. Copyright & Intellectual Property</h2>
        <p>
          PetiBoo does <strong>not</strong> intentionally reproduce, replicate,
          or imitate copyrighted characters, artworks, brands, or styles in a
          way that violates intellectual property laws.
        </p>

        <ul>
          <li>
            Generated images are <strong>new, original creations</strong>.
          </li>
          <li>
            References to “cartoon-inspired” styles describe visual aesthetics
            only.
          </li>
          <li>
            Outputs are not exact copies of any existing copyrighted works.
          </li>
        </ul>

        <p>
          Users are responsible for ensuring that their use of generated content
          complies with applicable copyright and trademark laws.
        </p>

        <h2>4. User-Uploaded Content Responsibility</h2>
        <p>
          Users retain ownership of images they upload. By uploading images, you
          confirm that:
        </p>

        <ul>
          <li>You own the rights to the images, or</li>
          <li>You have permission to use them</li>
        </ul>

        <p>
          PetiBoo is not responsible for copyright violations arising from
          user-uploaded content.
        </p>

        <h2>5. No Legal or Professional Advice</h2>
        <p>
          AI-generated content provided by PetiBoo is for personal,
          entertainment, and creative purposes only.
        </p>

        <p>
          Nothing generated by the Service constitutes legal, professional, or
          commercial advice.
        </p>

        <h2>6. Limitations of AI Output</h2>
        <p>
          While we strive for high-quality results, AI-generated images:
        </p>

        <ul>
          <li>May contain inaccuracies or visual artifacts</li>
          <li>May not meet subjective expectations</li>
          <li>Are provided “as is” without guarantees</li>
        </ul>

        <h2>7. Prohibited Use of AI Outputs</h2>
        <p>You agree not to use AI-generated content for:</p>

        <ul>
          <li>Illegal or harmful activities</li>
          <li>Impersonation or identity fraud</li>
          <li>Misleading or deceptive representations</li>
          <li>Training competing AI models without permission</li>
        </ul>

        <h2>8. Reporting Concerns</h2>
        <p>
          If you believe that generated content infringes intellectual property
          rights or violates ethical standards, please contact us promptly.
        </p>

        <h2>9. Changes to This Disclaimer</h2>
        <p>
          We may update this AI Ethics & Copyright Disclaimer from time to time.
          Updates will be posted on this page with a revised “Last updated” date.
        </p>

        <h2>10. Contact Us</h2>
        <p>
          If you have questions or concerns regarding AI ethics or copyright,
          contact us:
        </p>

        <ul>
          <li>
            Website:{' '}
            <a href="https://petiboo.co.uk/contact">
              https://petiboo.co.uk/contact
            </a>
          </li>
          <li>
            Email:{' '}
            <a href="mailto:contact@petiboo.co.uk">
              contact@petiboo.co.uk
            </a>
          </li>
        </ul>
      </section>
    </main>
  );
}
