export const metadata = {
  title: 'Terms of Service | PetiBoo',
  description:
    'Terms of Service for PetiBoo operated by Oasis Software Technology Limited.',
};

export default function TermsOfServicePage() {
  return (
    <main className="mx-auto w-full max-w-5xl px-6 py-12">
      <header className="mb-10">
        <h1 className="text-4xl font-bold tracking-tight text-slate-900">
          Terms of Service
        </h1>
        <p className="mt-3 text-sm text-slate-600">
          <strong>Last updated:</strong> 25 December 2025
        </p>
      </header>

      <section className="prose prose-slate max-w-none">
        <p>
          These Terms of Service (“Terms”) govern your access to and use of the
          PetiBoo website and services (“Service”), operated by{' '}
          <strong>Oasis Software Technology Limited</strong> (“Company”, “We”,
          “Us”, or “Our”).
        </p>

        <p>
          By accessing or using the Service, you agree to be bound by these
          Terms. If you do not agree with any part of these Terms, you must not
          use the Service.
        </p>

        <h2>1. Eligibility</h2>
        <p>
          You must be at least <strong>13 years old</strong> to use PetiBoo. By
          using the Service, you represent that you meet this requirement.
        </p>

        <h2>2. Description of the Service</h2>
        <p>
          PetiBoo provides an AI-powered service that allows users to upload
          photos of themselves and their pets to generate original caricature
          images.
        </p>

        <p>
          All outputs are generated by artificial intelligence and are intended
          for personal, non-commercial use unless otherwise stated.
        </p>

        <h2>3. User Accounts</h2>
        <p>
          To access certain features, you may be required to create an account.
          You are responsible for maintaining the confidentiality of your
          account credentials and for all activities that occur under your
          account.
        </p>

        <h2>4. User Content</h2>
        <h3>4.1 Uploaded Content</h3>
        <p>
          You retain ownership of the photos you upload (“User Content”). By
          uploading content, you grant Us a limited, non-exclusive, royalty-free
          license to process the content solely for the purpose of providing the
          Service.
        </p>

        <h3>4.2 Prohibited Content</h3>
        <p>You agree not to upload content that:</p>
        <ul>
          <li>Violates any law or regulation</li>
          <li>Infringes intellectual property or privacy rights</li>
          <li>Contains explicit, abusive, or hateful material</li>
          <li>Depicts minors in inappropriate ways</li>
          <li>Is misleading, fraudulent, or harmful</li>
        </ul>

        <p>
          We reserve the right to remove content or suspend accounts that
          violate these rules.
        </p>

        <h2>5. AI-Generated Content Disclaimer</h2>
        <p>
          The Service uses artificial intelligence to generate images. Outputs:
        </p>
        <ul>
          <li>Are algorithmically generated and may vary in style or quality</li>
          <li>Are not guaranteed to meet subjective expectations</li>
          <li>Are original and do not intentionally replicate copyrighted
          characters or artworks</li>
        </ul>

        <p>
          PetiBoo does not guarantee that generated images will be error-free or
          suitable for commercial or professional use.
        </p>

        <h2>6. Payments and Refunds</h2>
        <p>
          Certain features of the Service require payment. Payments are
          processed securely via <strong>Stripe</strong>.
        </p>

        <ul>
          <li>All prices are displayed before purchase</li>
          <li>We do not store payment card details</li>
          <li>Payment processors handle all sensitive financial information</li>
        </ul>

        <p>
          <strong>Money-Back Guarantee:</strong> If you are not satisfied, you
          may request a refund in accordance with our refund policy, provided
          the request meets eligibility requirements.
        </p>

        <h2>7. Intellectual Property</h2>
        <p>
          The Service, including its design, software, branding, and underlying
          technology, is owned by Oasis Software Technology Limited and is
          protected by intellectual property laws.
        </p>

        <p>
          You may not copy, modify, distribute, or reverse-engineer any part of
          the Service without our prior written consent.
        </p>

        <h2>8. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for unlawful purposes</li>
          <li>Attempt to bypass security or rate limits</li>
          <li>Scrape, crawl, or bulk-download content</li>
          <li>Exploit the Service for commercial resale without permission</li>
        </ul>

        <h2>9. Termination</h2>
        <p>
          We may suspend or terminate your access to the Service at any time,
          without prior notice, if you breach these Terms or misuse the Service.
        </p>

        <h2>10. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, Oasis Software Technology
          Limited shall not be liable for any indirect, incidental, special, or
          consequential damages arising from your use of the Service.
        </p>

        <p>
          The Service is provided on an “as is” and “as available” basis without
          warranties of any kind.
        </p>

        <h2>11. Indemnification</h2>
        <p>
          You agree to indemnify and hold harmless the Company from any claims,
          damages, or expenses arising from your use of the Service or violation
          of these Terms.
        </p>

        <h2>12. Governing Law</h2>
        <p>
          These Terms are governed by and construed in accordance with the laws
          of the <strong>United Kingdom</strong>.
        </p>

        <h2>13. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. Changes will be posted on
          this page with an updated “Last updated” date.
        </p>

        <h2>14. Contact Us</h2>
        <p>If you have any questions about these Terms, you can contact us:</p>
        <ul>
          <li>
            Website:{' '}
            <a href="https://petiboo.co.uk/contact">
              https://petiboo.co.uk/contact
            </a>
          </li>
          <li>
            Email:{' '}
            <a href="mailto:contact@petiboo.co.uk">
              contact@petiboo.co.uk
            </a>
          </li>
        </ul>
      </section>
    </main>
  );
}
